export type CountryDetails = {
    name:         {common:string,};
    tld:          string[];
    cca2:         string;
    ccn3:         string;
    cca3:         string;
    cioc:         string;
    independent:  boolean;
    status:       string;
    unMember:     boolean;
    currencies:   { [key: string]: {[key: string]:string} };
    idd:          string | number;
    capital:      string[];
    altSpellings: string[];
    region:       string;
    subregion:    string;
    languages:    string;
    translations: { [key: string]: Translation };
    latlng:       number[];
    landlocked:   boolean;
    area:         number;
    demonyms:     string;
    flag:         string;
    maps:         string;
    population:   number;
    fifa:         string;
    car:          string;
    timezones:    string[];
    continents:   string[];
    flags:        string;
    coatOfArms:   string;
    startOfWeek:  string;
    capitalInfo:  string;
    borders:      string[];
    gini:         { [key: string]: number };
    postalCode:   string;
};
